compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
main_process_port: 13121
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 3
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

#compute_environment: LOCAL_MACHINE
#debug: false
#distributed_type: NO      # ✅ 改为单卡
#downcast_bf16: 'no'
#enable_cpu_affinity: false
#gpu_ids: '2'                      # ✅ 只使用第 4 个 GPU
#machine_rank: 0
#main_training_function: main
#mixed_precision: fp16            # ✅ 使用混合精度
#num_machines: 1                  # ✅ 单机
#num_processes: 1                 # ✅ 与单卡一致
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false
